import { expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

test('route files exist with expected exports', () => {
  const root = import.meta.dir
  const files = [
    ['routes/HomeRoute.tsx', 'HomeRoute'],
    ['routes/RoutingRoute.tsx', 'RoutingRoute'],
    ['routes/RequirementsRoute.tsx', 'RequirementsRoute'],
    ['routes/ReviewRoute.tsx', 'ReviewRoute'],
    ['routes/DesignRoute.tsx', 'DesignRoute'],
    ['routes/TaskSplitRoute.tsx', 'TaskSplitRoute'],
    ['routes/DevelopmentRoute.tsx', 'DevelopmentRoute'],
    ['routes/OverallReviewRoute.tsx', 'OverallReviewRoute'],
    ['routes/ControlRoute.tsx', 'ControlRoute'],
  ] as const
  for (const [relativePath, exportName] of files) {
    const content = readFileSync(join(root, relativePath), 'utf8')
    expect(content.includes(`export function ${exportName}`)).toBe(true)
  }
})

test('index handles Ctrl+C through graceful backend shutdown', () => {
  const content = readFileSync(join(import.meta.dir, 'index.tsx'), 'utf8')
  const appContent = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(content.includes("import { App, getLatestBackendCleanupContext, runBackendCleanupFallback, stopBackendClient } from './app'")).toBe(true)
  expect(content.includes('exitOnCtrlC: false')).toBe(true)
  expect(content.includes("for (const signal of ['SIGINT', 'SIGTERM', 'SIGHUP'] as const)")).toBe(true)
  expect(content.includes("await stopBackendClient({ reason: 'signal', forceKillAfterMs: 30000 })")).toBe(true)
  expect(content.includes('if (!stopResult.graceful || stopResult.signalEscalatedToSigkill)')).toBe(true)
  expect(content.includes('await runBackendCleanupFallback(getLatestBackendCleanupContext())')).toBe(true)
  expect(content.includes('process.exit(exitCodeForSignal(signal))')).toBe(true)
  expect(content.includes("onExitRequest={() => shutdownFromSignal('SIGINT')}")).toBe(true)
  expect(appContent.includes('onExitRequest?: () => void | Promise<void>')).toBe(true)
  expect(appContent.includes("if (event.name === 'c' && event.ctrl)")).toBe(true)
  expect(appContent.includes('await props.onExitRequest?.()')).toBe(true)
  expect(appContent.includes('export function getLatestBackendCleanupContext(): BackendCleanupContext')).toBe(true)
  expect(appContent.includes('export function runBackendCleanupFallback(context: BackendCleanupContext)')).toBe(true)
})

test('development route renders milestone checklist and app status includes current milestone support', () => {
  const routeContent = readFileSync(join(import.meta.dir, 'routes/DevelopmentRoute.tsx'), 'utf8')
  const appContent = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(routeContent.includes('里程碑与任务清单')).toBe(true)
  expect(routeContent.includes("☑")).toBe(true)
  expect(routeContent.includes("☐")).toBe(true)
  expect(appContent.includes('current_milestone:')).toBe(true)
  expect(appContent.includes('buildDevelopmentStatusLines')).toBe(true)
})

test('overall review route is wired into the app shell', () => {
  const routeContent = readFileSync(join(import.meta.dir, 'routes/OverallReviewRoute.tsx'), 'utf8')
  const appContent = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(routeContent.includes('复核')).toBe(true)
  expect(appContent.includes("route() === 'overall-review'")).toBe(true)
  expect(appContent.includes('<OverallReviewRoute snapshot={overallReviewSnapshot()} />')).toBe(true)
})

test('app renders a fixed footer status host when no free-text prompt is active', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  const footerProgress = readFileSync(join(import.meta.dir, 'footerProgress.ts'), 'utf8')
  expect(content.includes('function FooterStatusHost')).toBe(true)
  expect(content.includes('pendingHitl: boolean')).toBe(true)
  expect(content.includes("const isError = createMemo(() => props.status === 'error' || props.status === 'failed')")).toBe(true)
  expect(content.includes("if (isWaitingForHitl()) return '等待人工输入'")).toBe(true)
  expect(content.includes("if (isError()) return '运行失败'")).toBe(true)
  expect(content.includes("if (isCompleted()) return '已完成'")).toBe(true)
  expect(content.includes("if (isError()) return '当前阶段发生错误，请查看上方日志。'")).toBe(true)
  expect(content.includes("if (isCompleted()) return '流程已完成，可退出界面。'")).toBe(true)
  expect(content.includes("if (isCompleted()) return '所有阶段已收尾，结果文件已写入项目目录。'")).toBe(true)
  expect(content.includes("if (isWaitingForHitl()) return '存在待处理 HITL，请回复问题。'")).toBe(true)
  expect(content.includes("if (isBooting()) return '⠦ 智能体启动中...'")).toBe(true)
  expect(content.includes('lines.push(`action: ${snapshot.currentAction}`)')).toBe(true)
  expect(content.includes('lines.push(`stage: ${snapshot.activeStageLabel || snapshot.activeStage}')).toBe(true)
  expect(content.includes('系统执行智能体任务中，输入框会在需要人类交互时自动恢复。')).toBe(true)
  expect(content.includes('请根据右侧问题文件或日志内容继续回复。')).toBe(true)
  expect(content.includes('pendingHitl={displayAppSnapshot().pendingHitl}')).toBe(true)
  expect(content.includes('routingWorkers: routingSnapshot().workers')).toBe(true)
  expect(footerProgress.includes("import { stageBusyLabel as resolveStageBusyLabel, stageProgressKey } from './stageRegistry'")).toBe(true)
  expect(footerProgress.includes("case 'routing':")).toBe(true)
  expect(content.includes('function FooterPromptHost')).toBe(true)
  expect(content.includes('focusToken={footerPromptFocusToken()}')).toBe(true)
  expect(content.includes("import { PromptInputPanel } from './ui/PromptInputPanel'")).toBe(true)
  expect(content.includes('<PromptInputPanel')).toBe(true)
  expect(content.includes("mode={props.active.promptType === 'multiline' ? 'multiline' : 'singleline'}")).toBe(true)
  expect(content.includes('showSubmitHelper={false}')).toBe(true)
  expect(content.includes('onBack={allowBack() ? () => void props.onSubmit(backValue()) : undefined}')).toBe(true)
  expect(content.includes('question:')).toBe(false)
  expect(content.includes('Ctrl+L 查看完整日志')).toBe(false)
})

test('app derives pending HITL from active prompt so home snapshot stays consistent while waiting for reply', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(content.includes('function isHitlPrompt')).toBe(true)
  expect(content.includes('function buildPromptBackedHitlSnapshot')).toBe(true)
  expect(content.includes('function buildVisibleHitlSnapshot')).toBe(true)
  expect(content.includes('function buildPromptBackedAttentionSnapshot')).toBe(true)
  expect(content.includes('function resolvePromptRequiresAttention')).toBe(true)
  expect(content.includes('function resolvePromptAttentionReason')).toBe(true)
  expect(content.includes('function resolveHitlQuestionPath')).toBe(true)
  expect(content.includes('const displayHitlSnapshot = createMemo(() => buildVisibleHitlSnapshot(prompt(), hitlSnapshot(), status()))')).toBe(true)
  expect(content.includes("pendingHitl: visibleHitl.pending || (base.pendingHitl && status() === 'awaiting-input')")).toBe(true)
  expect(content.includes('return EMPTY_HITL_SNAPSHOT')).toBe(true)
  expect(content.includes('lines.push(`pending_hitl: ${snapshot.pendingHitl ? \'yes\' : \'no\'}`)')).toBe(true)
  expect(content.includes('lines.push(`pending_attention: ${snapshot.pendingAttention ? \'yes\' : \'no\'}`)')).toBe(true)
  expect(content.includes('<HomeRoute snapshot={displayAppSnapshot()} hitl={displayHitlSnapshot()} agents={homeAgents()} />')).toBe(true)
  expect(content.includes('questionPath: resolveHitlQuestionPath(active?.payload) || fallback.questionPath')).toBe(true)
  expect(content.includes('attachCommand: resolveAgentAttachCommand(active?.payload) || fallback.attachCommand')).toBe(true)
})

test('agent recovery select prompts display tmux attach command hints', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(content.includes('function buildAgentRecoveryHintLines')).toBe(true)
  expect(content.includes("recoveryKind === 'agent_manual_intervention' || recoveryKind === 'agent_ready_timeout'")).toBe(true)
  expect(content.includes('payload.attach_command ?? payload.attachCommand')).toBe(true)
  expect(content.includes('payload.session_name ?? payload.sessionName')).toBe(true)
  expect(content.includes('`tmux attach -t ${sessionName}`')).toBe(true)
  expect(content.includes("title.includes('需要人工介入') || title.includes('智能体启动超时')")).toBe(true)
  expect(content.includes('const lines: string[] = [...buildAgentRecoveryHintLines(props.active.payload)]')).toBe(true)
  expect(content.includes('hintLines={hintLines()}')).toBe(true)
})

test('app reports recent TUI presence and client sends it through ui.presence with debounce', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  const client = readFileSync(join(import.meta.dir, 'backend/client.ts'), 'utf8')
  expect(content.includes('const PRESENCE_REPORT_DEBOUNCE_MS = 1500')).toBe(true)
  expect(content.includes('const lastPresenceAtByReason = new Map<string, number>()')).toBe(true)
  expect(content.includes('const reportPresence = (reason: string, focus: ShellFocus = shellFocus()) => {')).toBe(true)
  expect(content.includes('if (now - lastAt < PRESENCE_REPORT_DEBOUNCE_MS) return')).toBe(true)
  expect(content.includes("client.sendPresence(normalizedReason, focus)")).toBe(true)
  expect(content.includes("if (event.name) reportPresence('keyboard')")).toBe(true)
  expect(content.includes("reportPresence('mouse')")).toBe(true)
  expect(content.includes("reportPresence('prompt-open', nextFocus)")).toBe(true)
  expect(client.includes("sendPresence(reason: string, shellFocus: string): void")).toBe(true)
  expect(client.includes("void this.request('ui.presence', {")).toBe(true)
  expect(client.includes('shell_focus: shellFocus')).toBe(true)
  expect(client.includes('}).catch(() => undefined)')).toBe(true)
})

test('app keeps terminal stage failures sticky and does not let stale progress events revive running state', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  const stageStatus = readFileSync(join(import.meta.dir, 'stageStatus.ts'), 'utf8')
  expect(content.includes("import {")).toBe(true)
  expect(content.includes("from './stageStatus'")).toBe(true)
  expect(content.includes('const [stageCursor, setStageCursor] = createSignal(EMPTY_STAGE_CURSOR)')).toBe(true)
  expect(content.includes('if (!shouldAcceptProgressEvent(stageCursor(), event.payload)) return')).toBe(true)
  expect(content.includes("setStageCursor((prev) => markTerminalStage(prev))")).toBe(true)
  expect(content.includes("if (event.type === 'progress.start') {")).toBe(true)
  expect(content.includes("if (event.type === 'progress.start') {\n      setStatus('running')")).toBe(false)
  expect(stageStatus.includes('export function applyStageChanged(')).toBe(true)
  expect(stageStatus.includes('export function shouldAcceptProgressEvent(')).toBe(true)
  expect(stageStatus.includes('export function markTerminalStage(')).toBe(true)
})

test('app isolates dialog, log, prompt, and content focus in the new shell layout', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(content.includes("type ShellFocus = 'content' | 'prompt' | 'log' | 'dialog'")).toBe(true)
  expect(content.includes('type DocumentPreviewState = {')).toBe(true)
  expect(content.includes('function resolvePreviewPath')).toBe(true)
  expect(content.includes('function resolvePreviewTitle')).toBe(true)
  expect(content.includes('function resolvePromptDocumentPath')).toBe(true)
  expect(content.includes('function DialogOverlay')).toBe(true)
  expect(content.includes('backgroundColor={RGBA.fromInts(0, 0, 0, 255)}')).toBe(true)
  expect(content.includes('function DocumentPreviewLayer')).toBe(true)
  expect(content.includes('const footerPrompt = createMemo<PromptState | null>(() => {')).toBe(true)
  expect(content.includes('const dialogPrompt = createMemo<PromptState | null>(() => {')).toBe(true)
  expect(content.includes('const [documentPreviewOpen, setDocumentPreviewOpen] = createSignal(false)')).toBe(true)
  expect(content.includes('const promptPreview = createMemo<DocumentPreviewState | null>(() => {')).toBe(true)
  expect(content.includes('const active = dialogPrompt() ?? footerPrompt()')).toBe(true)
  expect(content.includes('const activeDocumentPreview = createMemo<DocumentPreviewState | null>(() => (documentPreviewOpen() ? promptPreview() : null))')).toBe(true)
  expect(content.includes('const [focusBeforeLog, setFocusBeforeLog] = createSignal<ShellFocus>(\'content\')')).toBe(true)
  expect(content.includes("const [logOpenGeneration, setLogOpenGeneration] = createSignal(0)")).toBe(true)
  expect(content.includes('function allocateShellHeights')).toBe(true)
  expect(content.includes('const footerMin = footerIsPrompt ? 13 : 6')).toBe(true)
  expect(content.includes('const shellHeights = createMemo(() => allocateShellHeights(dimensions().height, Boolean(footerPrompt()), showLogs()))')).toBe(true)
  expect(content.includes('1-5 页面 | F1-F10 全局动作 | Ctrl+L 日志抽屉 | 日志展开后仍可输入')).toBe(false)
  expect(content.includes('日志已展开，可继续输入 | Ctrl+↑/↓/PgUp/PgDn/Home/End 滚动 | Ctrl+L 收起')).toBe(true)
  expect(content.includes("if (event.name === 'l' && event.ctrl)")).toBe(true)
  expect(content.includes("if (footerPrompt() && shellFocus() === 'prompt') return")).toBe(true)
  expect(content.includes('const toggleLogs = () => {')).toBe(true)
  expect(content.includes('const openLogs = () => {')).toBe(true)
  expect(content.includes('const closeLogs = () => {')).toBe(true)
  expect(content.includes('const handleLogNavigation = (event: { name: string; ctrl?: boolean; preventDefault: () => void }) => {')).toBe(true)
  expect(content.includes("if (!showLogs() || !event.ctrl) return false")).toBe(true)
  expect(content.includes('setLogAutoFollow(true)')).toBe(true)
  expect(content.includes('logScrollbox.scrollTop += delta')).toBe(true)
  expect(content.includes('setLogOpenGeneration((prev) => prev + 1)')).toBe(true)
  expect(content.includes('stickyScroll={logAutoFollow()}')).toBe(true)
  expect(content.includes('stickyStart="bottom"')).toBe(true)
  expect(content.includes('<Show when={showLogs() ? logOpenGeneration() : null} keyed>')).toBe(true)
  expect(content.includes('setShellFocus(footerPrompt() ? \'prompt\' : resolveFocusAfterLogClose())')).toBe(true)
  expect(content.includes('focused={shellFocus() === \'prompt\'}')).toBe(true)
  expect(content.includes('rememberHistory={!isHitlPrompt(props.active)}')).toBe(true)
  expect(content.includes("if (event.name === 'k' && event.ctrl)")).toBe(true)
  expect(content.includes('const preview = promptPreview()')).toBe(true)
  expect(content.includes('setDocumentPreviewOpen(true)')).toBe(true)
  expect(content.includes('setDocumentPreviewOpen(false)')).toBe(true)
  expect(content.includes('Ctrl+K 关闭，Esc 关闭，↑/↓/PgUp/PgDn/Home/End 滚动')).toBe(true)
  expect(content.includes('Ctrl+K 查看文档')).toBe(true)
  expect(content.includes('dialogActive={!Boolean(activeDocumentPreview())}')).toBe(true)
  expect(content.includes('<DocumentPreviewLayer')).toBe(true)
  expect(content.includes('log_open: yes')).toBe(true)
  expect(content.includes('<scrollbox flexGrow={1} scrollY>')).toBe(true)
  expect(content.includes('height={shellHeights().top}')).toBe(true)
  expect(content.includes('height={shellHeights().log}')).toBe(true)
  expect(content.includes('height={shellHeights().footer}')).toBe(true)
  expect(content.includes("import { promptAllowsBack, resolvePromptBackValue, withPromptBackOption } from './promptBack'")).toBe(true)
  expect(content.includes('options={selectOptions()}')).toBe(true)
  expect(content.includes('allowBack={promptAllowsBack(props.active.payload)}')).toBe(true)
  expect(content.includes('backValue={resolvePromptBackValue(props.active.payload)}')).toBe(true)
  expect(content.includes("import { resolvePromptResponseTransition } from './promptTransition'")).toBe(true)
  expect(content.includes('const transition = resolvePromptResponseTransition(current.id, prompt())')).toBe(true)
  expect(content.includes('if (transition.clearPrompt) setPrompt(null)')).toBe(true)
})

test('app uses structured log entries and block rendering for log readability', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  const logging = readFileSync(join(import.meta.dir, 'logging.ts'), 'utf8')
  expect(logging.includes("export type LogKind = 'stage' | 'summary' | 'runtime' | 'warning' | 'error' | 'hitl' | 'plain'")).toBe(true)
  expect(logging.includes('export type LogEntry = {')).toBe(true)
  expect(logging.includes('LOG_ENTRY_LIMIT')).toBe(true)
  expect(logging.includes('MAX_LINES_PER_ENTRY')).toBe(true)
  expect(content.includes('function LogEntryCard')).toBe(true)
  expect(content.includes('appendRuntimeLog')).toBe(true)
  expect(logging.includes("kind: 'stage'")).toBe(true)
  expect(logging.includes("kind: 'summary'")).toBe(true)
  expect(logging.includes("kind: 'runtime'")).toBe(true)
  expect(logging.includes("kind: 'warning'")).toBe(true)
  expect(logging.includes("kind: 'error'")).toBe(true)
  expect(logging.includes("kind: 'hitl'")).toBe(true)
  expect(logging.includes('执行摘要')).toBe(true)
  expect(logging.includes('运行时信息')).toBe(true)
  expect(content.includes("if (kind === 'hitl') {")).toBe(true)
  expect(content.includes('<For each={logs()}>')).toBe(true)
  expect(content.includes('<LogEntryCard entry={entry} />')).toBe(true)
  expect(content.includes("const [showLogs, setShowLogs] = createSignal(false)")).toBe(true)
  expect(content.includes("requestAction('run.list'")).toBe(true)
})

test('app aggregates running workers for home overview and HomeRoute uses the new overview fields', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  const homeRoute = readFileSync(join(import.meta.dir, 'routes/HomeRoute.tsx'), 'utf8')
  const types = readFileSync(join(import.meta.dir, 'types.ts'), 'utf8')
  const homeAgents = readFileSync(join(import.meta.dir, 'homeAgents.ts'), 'utf8')
  expect(types.includes('export type HomeAgentItem = {')).toBe(true)
  expect(types.includes('activeStageLabel: string')).toBe(true)
  expect(types.includes('pendingAttention: boolean')).toBe(true)
  expect(types.includes('pendingAttentionReason: string')).toBe(true)
  expect(types.includes('pendingAttentionSince: string')).toBe(true)
  expect(types.includes('vendor?: string')).toBe(true)
  expect(types.includes('model?: string')).toBe(true)
  expect(types.includes('resolvedModel?: string')).toBe(true)
  expect(types.includes('reasoningEffort?: string')).toBe(true)
  expect(types.includes('agentConfigLabel: string')).toBe(true)
  expect(types.includes('attachCommand: string')).toBe(true)
  expect(content.includes('activeStageLabel: String(payload.active_stage_label ?? payload.activeStageLabel ?? \'等待中\')')).toBe(true)
  expect(content.includes('pendingAttention: Boolean(payload.pending_attention ?? payload.pendingAttention)')).toBe(true)
  expect(content.includes('pendingAttentionReason: String(payload.pending_attention_reason ?? payload.pendingAttentionReason ?? \'\')')).toBe(true)
  expect(content.includes('pendingAttentionSince: String(payload.pending_attention_since ?? payload.pendingAttentionSince ?? \'\')')).toBe(true)
  expect(homeAgents.includes('const LIVE_WORKER_HEALTH_STATUSES = new Set([\'alive\', \'observe_error\', \'provider_auth_error\'])')).toBe(true)
  expect(homeAgents.includes('export function buildHomeAgents(')).toBe(true)
  expect(homeAgents.includes('export function resolveHomeAgentState(worker: WorkerSnapshot): string')).toBe(true)
  expect(homeAgents.includes('export function isBusyWorker(worker: WorkerSnapshot): boolean')).toBe(true)
  expect(homeAgents.includes('const stageRoute = stageRouteForAction(activeStage)')).toBe(true)
  expect(homeAgents.includes('const HOME_AGENT_STATE_RANK')).toBe(true)
  expect(homeAgents.includes("if (agentState === 'DEAD' || agentState === 'STARTING') return true")).toBe(true)
  expect(homeAgents.includes('if (worker.sessionExists !== undefined) return worker.sessionExists')).toBe(true)
  expect(content.includes("currentTaskRuntimeStatus: String(value.current_task_runtime_status ?? value.currentTaskRuntimeStatus ?? '')")).toBe(true)
  expect(content.includes("resultStatus: String(value.result_status ?? value.resultStatus ?? '')")).toBe(true)
  expect(content.includes("vendor: String(value.vendor ?? '')")).toBe(true)
  expect(content.includes("model: String(value.model ?? '')")).toBe(true)
  expect(content.includes("resolvedModel: String(value.resolved_model ?? value.resolvedModel ?? '')")).toBe(true)
  expect(content.includes("reasoningEffort: String(value.reasoning_effort ?? value.reasoningEffort ?? '')")).toBe(true)
  expect(content.includes('{ source: \'control\', workers: controlSnapshot()?.workers ?? [] }')).toBe(true)
  expect(content.includes('displayAppSnapshot().activeStage,')).toBe(true)
  expect(homeRoute.includes('智能体状态')).toBe(true)
  expect(homeRoute.includes('const HOME_AGENT_SPINNER_FRAMES = [')).toBe(true)
  expect(homeRoute.includes('function AgentStatusMarker(props: { agentState: string })')).toBe(true)
  expect(homeRoute.includes("const marker = createMemo(() => (isBusy() ? HOME_AGENT_SPINNER_FRAMES[frameIndex()] : '•'))")).toBe(true)
  expect(homeRoute.includes("if (normalizedState() === 'DEAD') return '❌'")).toBe(true)
  expect(homeRoute.includes('<AgentStatusMarker agentState={agent.agentState} />')).toBe(true)
  expect(homeRoute.includes('function agentSummary(agent: HomeAgentItem): string')).toBe(true)
  expect(homeRoute.includes('agent.agentConfigLabel')).toBe(true)
  expect(homeRoute.includes('`${agent.source} |')).toBe(false)
  expect(homeRoute.includes('{agent.attachCommand}')).toBe(true)
  expect(homeRoute.includes('当前没有可显示的智能体状态。')).toBe(true)
  expect(homeRoute.includes('当前阶段: {props.snapshot.activeStageLabel || \'等待中\'}')).toBe(true)
  expect(homeRoute.includes('question: {props.hitl.questionPath}')).toBe(true)
  expect(homeRoute.includes('{props.hitl.attachCommand}')).toBe(true)
  expect(homeRoute.includes('Ctrl+L 查看完整日志')).toBe(true)
  expect(homeRoute.includes('<Show when={props.snapshot.pendingAttention}>')).toBe(true)
  expect(homeRoute.includes('macOS 提醒中:')).toBe(true)
  expect(homeRoute.includes('当前没有进行中的 macOS 提醒')).toBe(false)
  expect(homeRoute.includes('当前 run')).toBe(false)
  expect(homeRoute.includes('最近产物')).toBe(false)
  expect(homeRoute.includes('快捷动作')).toBe(false)
})

test('app bridges mouse selection copy to the system clipboard at the root shell', () => {
  const content = readFileSync(join(import.meta.dir, 'app.tsx'), 'utf8')
  expect(content.includes('onMouseUp={(event) => {')).toBe(true)
  expect(content.includes('const selectedText = renderer.getSelection?.()?.getSelectedText?.()')).toBe(true)
  expect(content.includes('void copyCurrentSelection(renderer)')).toBe(true)
  expect(content.includes('event.stopPropagation()')).toBe(true)
})
